name: Build

on:
  push:
    # Do not run on tag pushes
    branches: '**'
    # Only run when;
    paths:
      # any Rust code has changed,
      - "**.rs"
      # this workflow has changed,
      - ".github/workflows/build.yml"
      # dependencies have changed,
      - "Cargo.lock"
  # or a rebuild is manually called.
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Create `out/`
        run: mkdir out

      # Install Rust on the various platforms

      - name: Install Rust for macOS
        if: matrix.os == 'macos-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin

      - name: Install Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Lint code
        run: cargo clippy

      - name: Run tests
        run: cargo test --no-default-features

      - name: Build macOS ARM
        if: matrix.os == 'macos-latest'
        run: |
          cargo build --target=aarch64-apple-darwin --release --no-default-features
          zip -r out/ferium-macos-arm.zip -j target/aarch64-apple-darwin/release/ferium

      - name: Upload build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: out/ferium*.zip
          if-no-files-found: error
